# Generated by Django 2.0.6 on 2018-06-03 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menuName', models.CharField(max_length=30)),
                ('menuImg', models.CharField(max_length=200)),
                ('menuLink', models.CharField(max_length=200)),
            ],
        ),
    ]
